// User
export const UPDATE_CREDENTIALS = "UPDATE_CREDENTIALS";
export const UPDATE_ERROR = "UPDATE_ERROR";
export const UPDATE_FETCHING_STATE = "UPDATE_FETCHING_STATE"
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_TO_FAVORITES";
export const LOGOUT_USER = "LOGOUT_USER";

//Player
export const UPDATE_HOME_DATA = "UPDATE_HOME_DATA";
export const UPDATE_HOME_FETCHING_STATE = "UPDATE_FETCHING_STATE";
export const ADD_TO_QUEUE = "ADD_TO_QUEUE";
export const UPDATE_QUEUE = "UPDATE_QUEUE";
export const CLEAR_QUEUE = "CLEAR_QUEUE";
export const UPDATE_IS_PLAYING = "UPDATE_IS_PLAYING";
export const UPDATE_PLAYING_INDEX = "UPDATE_PLAYING_INDEX";

